### ISSUE TITLE
file level and dataset level download display

### ISSUE THREAD

**Issue by jmjamison** [CDLUC3/counter-processor#18]
This may be more a question than an issue. I'm running Dataverse 4.20.  If a file is downloaded from the file display page the downloads are displayed there but not on the dataset level page.   
![dataset-level-page](https://user-images.githubusercontent.com/229689/89326550-5379db00-d63f-11ea-94c2-fb24571f5c6f.JPG)
![file-level-page](https://user-images.githubusercontent.com/229689/89326554-54ab0800-d63f-11ea-842a-1bbd85e4a45e.JPG)

**Comment by dlowenberg** [comment]
Hi @jmjamison this would be a question for the Dataverse team about their implementation and what they are choosing to display

**Comment by jmjamison** [comment]
Thank you - I'll post the question to them.
