### ISSUE TITLE
size data is missing from output report

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/counter-processor#4]
I do not see request sizes being output from the processor.  Need to look at why.

**Comment by pdurbin** [comment]
@sfisher hi! I just created pull request #5 for fix this. Please let me and @matthew-a-dunlap know what you think. Thanks!

**Comment by sfisher** [comment]
Thanks.  It's all merged and I've created this tag/release, also. https://github.com/CDLUC3/counter-processor/releases/tag/v0.1

**Comment by pdurbin** [comment]
@sfisher thank you! I just tested 0.1 and now we have "volume" in the SUSHI JSON reports. I just pushed an example file to https://github.com/IQSS/dataverse/commit/36fa81a that we're using for testing.
